# Generated by Django 5.2.8 on 2025-11-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(help_text='Enter Employee Name', max_length=20)),
                ('age', models.IntegerField(help_text='Enter age of Employee')),
                ('dob', models.DateField(help_text='Enter Date of Birth')),
                ('reg_no', models.IntegerField(help_text='Enter the Register Number')),
            ],
        ),
    ]
